services:
  amazon-linux-2:
    build: .
    container_name: amazon-linux-2
    tty: true
    privileged: true
    ports:
      - "22222:22"
      - "18880:80"
    volumes:
      - type: bind
        source: ./workspace
        target: /workspace
